### ISSUE TITLE
[建议] 改变物品的读取方式

### ISSUE THREAD

**Issue by ghost** [CarmJos/UserPrefix#15]
### **功能简述**
物品自动识别，提供更简单的读取方式

### **需求来源**
现在是ItemStack读取，虽然自由了，但是错误率很高，配置困难

### **功能参考**(可选)
暂无

### **附加内容**
暂无

**Comment by CarmJos** [comment]
您好，在最新的提交 969844dae94fd1ac86c1b455de3f30039be04d99 中，我对配置文件、插件接口等内容做出大量更新。


**在使用本次提交的版本前，请您先备份当前配置文件，并重新生成全部配置。**

### 更新内容
鉴于 ItemStack 原生配置使用困难且易错，本次提交中不再使用原生配置，而是使用来自 MineConfiguration 项目中 ItemConfig 的配置去加载。这使得配置量大大减轻，也满足了绝大部分人的使用需求。修改后的配置如下所示：
```yaml
itemUsing:
  type: DIAMOND
  name: "&b&lPro &b会员前缀"
  lore:
    - "&7Pro会员专属称号"
    - ""
    - "&f尊贵的Pro会员专属称号。"
    - "&f您将获得多种特权与更好的游戏体验。"
    - ""
    - "&a✔ 您正在使用该前缀"
  enchants:
    PROTECTION_ENVIRONMENTAL: 1 #加一个附魔这样看上去就像是选中了的
  flags:
    - HIDE_ENCHANTS # 隐藏附魔显示
```

于此同时，针对可能存在的配置上的失误，在本次提交中也对各种情况提供了不同的提示，方便使用者确定问题。
```text
...
[UserPrefix] UserPrefix 3.0.0 开始启动...
[UserPrefix] 加载插件配置...
[UserPrefix] 加载前缀配置...
[UserPrefix] [ERROR] 在加载前缀 /home/container/plugins/UserPrefix/prefixes/example-prefix.yml 时出错，请检查配置！
[UserPrefix] [ERROR] Error occurred when loading prefix #/home/container/plugins/UserPrefix/prefixes/example-prefix.yml !
java.lang.Exception: Invalid material name: INK_SACK
...
```

### 补充
由于本次更新的范围较大，并大量采用了本人开发的其他高级类库，因此从本版本开始插件的大小可能不在“轻量”。但整体运行的效率较之前版本会有提升，代码也变得更加简介易懂。

由于采用了内嵌在代码中的配置库，因此自本版本开始需要额外维护本插件的英文版本介绍与配置(config.yml、messages.yml)。如果您有空闲时间，十分欢迎您贡献您的一份力，为UserPrefix提供相关翻译。
