### ISSUE TITLE
[建议] 是否可以加一个返回主菜单的按钮

### ISSUE THREAD

**Issue by Msyial** [CarmJos/UserPrefix#20]
### **功能简述**
当玩家打开前缀仓库后除了常规的选择前缀与上下页以外 知否可以添加一个返回上一个菜单的按钮？按钮的指令可以管理人员自己设置。

### **需求来源**
试玩家使用菜单时更加的方便

### **功能参考**(可选)
![image](https://user-images.githubusercontent.com/61540044/161501033-e6450997-8b72-4bb6-99b1-9097c25ce269.png)

### **附加内容**
最好可以让开发者自己选择物品，lore和名称

**Comment by CarmJos** [comment]
您好，在最新的提交 969844dae94fd1ac86c1b455de3f30039be04d99 中，我对配置文件、插件接口等内容做出大量更新，同时实现了您所提到的功能需求。

**在使用本次提交的版本前，请您先备份当前配置文件，并重新生成全部配置。**

### 使用方法

在插件的 `config.yml`中的 `gui.items` 配置下，新增 `back` 图标配置，它看起来是这样的：
```yaml
    back:
      type: BARRIER
      name: '&c&l返回'
      lore:
      - '&f点击即可返回上一菜单'
      slot: 49
      actions:
      - '[CHAT] /menu'
```

在该配置中：
- `type` 代表图标物品的材质
- `name` 代表图标物品显示的名称，支持PlaceholderAPI变量。
- `lore` 代表图片物品介绍内容，支持PlaceholderAPI变量。
- `slot` 代表图标在GUI中所在格
  - 若您需要同时在多个格子中显示该物品，则可以使用名为 `slots` 的list替代该配置 
- `actions` 代表点击图标执行的操作

本次提交支持了一下操作类型
- `CHAT` 以玩家聊天的形式发送，若需要发送指令则添加“/”前缀
- `CONSOLE` 以后台的形式发送指令
- `SOUND` 向玩家发送声音
- `MESSAGE` 向玩家发送一条消息，支持PlaceholderAPI变量
- `CLOSE` 关闭当前GUI

若您需要限定玩家点击的类型，如左键、右键等，则可以添加在操作类型后，以“:”分割，如：
- `[CLOSE:LEFT]` 代表左键点击关闭
- `[MESSAGE:MIDDLE] HELLO WORLD` 代表鼠标中间点击发送消息

详细点击类型见 `org.bukkit.event.inventory.ClickType` 。


### 补充
由于本次更新的范围较大，并大量采用了本人开发的其他高级类库，因此从本版本开始插件的大小可能不在“轻量”。但整体运行的效率较之前版本会有提升，代码也变得更加简介易懂。

由于采用了内嵌在代码中的配置库，因此自本版本开始需要额外维护本插件的英文版本介绍与配置(config.yml、messages.yml)。如果您有空闲时间，十分欢迎您贡献您的一份力，为UserPrefix提供相关翻译。
