### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by Kawa1Ares** [CarmJos/UserPrefix#21]
### **功能简述**
添加玩家语言管理
就像deluxechat那样(我对BukkitAPI的语言系统不太熟悉)
[%UserPrefix_prefix%]%player% >> %message% (就像这样)

### **需求来源**
杂七杂八的聊天插件太杂乱了，还不如一个插件囊括全部（）

### **附加内容**
卡姆女装！(小声)

**Comment by CarmJos** [comment]
自 2.2.0 版本起，已提供原生支持的辽西消息修改插件，在配置文件中它长这样：
```yaml
# 功能设定
functions:
  # 聊天功能设定
  # - 我不推荐使用本插件的聊天功能，而是建议使用其他的聊天插件。
  # - 本插件仅仅提供了**最基本**的格式变量支持，不包含其他任何功能。
  # - 注意聊天格式需要遵守Bukkit原格式，即不得缺失 “%1$s” 和 “%2$s” 。
  # - 本插件的聊天功能不影响其他插件对聊天事件的操作。
  chat:
    # 是否开启本功能
    enable: false
    # 聊天的格式，注意 “%1$s” 和 “%2$s” 不可缺少。
    # - %1$s -> 玩家名
    # - %2$s -> 聊天内容
    format: <%1$s> %2$s
```

按照你的需求，`format` 的配置应该是 `"&7[&r%UserPrefix_prefix%&7] &f%1$s &8>>&r %2$s"` 。

### 另

我很乐意满足粉丝的_奇怪癖好_，但前提是可以给我提供对应的物件。我的身高是202cm，体重116kg，请问有满足我体形的女装吗？
