### ISSUE TITLE
有没有一种可能，新增打开GUI指令自定义（？）

### ISSUE THREAD

**Issue by Coquettishpig** [CarmJos/UserPrefix#23]
#打开gui指令
- 'us'
- 'up'

**Comment by CarmJos** [comment]
在插件jar包内的 `plugin.yml` 中，有对应指令的配置，如须修改，请添加你想要的指令到 aliases 下，他看起来是这样的：

```yml
commands:
  UserPrefix:
    aliases:
      - prefix
      - up # 如果你需要的话
      - us # 如果你需要的话
    description: "用户前缀系统玩家指令，用于打开前缀GUI。"
```
