### ISSUE TITLE
feat(func): 支持使用头颅作为称号图标

### ISSUE THREAD

**Issue by postyizhan** [CarmJos/UserPrefix#27]
### **功能简述**
在界面 /userprefix 中可以使用头颅来显示称号

### **需求来源**
我使用dm菜单配合一个插件做了个正版验证，dm菜单中的图标使用了 eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjc3MDVlM2U5OTdlNWNlNTIxNjY2M2M5ZTY0YjM5NmZhNDNlZGRlODI1NWZkOTEwZjBjYzgxYTAzMjVlNmIifX19 这个头颅(来自https://minecraft-heads.com/custom-heads/miscellaneous/4451-mojang)
我想在 userprefix 保持统一

**Comment by CarmJos** [comment]
我前天把前缀项目详细的看了遍。最终打算单独为每一件物品提供original选项以支持原生ItemStack物品的配置(同先前一样)。于此同时，我会在游戏内额外提供"/upa set <前缀ID> <类型>"指令以支持直接设置原生物品到配置文件中。

**Comment by usernameOHH** [comment]
啊可以的，既然能设置那就是也能直接改配置文件对吧?

**Comment by Coquettishpig** [comment]
我挺好奇是配合哪个插件做的正版验证，我找不到好的xd

**Comment by usernameOHH** [comment]
[机制]DoomsdayVerify —— 支持微软登录的正版验证 [1.8-1.15]
https://www.mcbbs.net/thread-1252309-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by Coquettishpig** [comment]
这个我觉得有一点点麻烦xd，好像做到那种点击就自动验证的xd

**Comment by usernameOHH** [comment]
我想不到怎么样才能做到你说的效果0.0

**Comment by Coquettishpig** [comment]
没事哈哈，麻烦了，我先去研究一下

**Comment by CarmJos** [comment]
> 啊可以的，既然能设置那就是也能直接改配置文件对吧?

是的，但是配置文件比较复杂，看起来像是这样：

```yaml
#...

item-using:
  original:
    ==: org.bukkit.inventory.ItemStack
    type: DIAMOND
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "&b&lVIP Prefix"
      enchants:
        PROTECTION_ENVIRONMENTAL: 1
      lore:
        - ""
        - "&a✔ Selected"

#...
```

original类型物品支持所有MineCraft配置类型，详细配置方式请参考[ItemStack Serialization(物品序列化)](https://www.spigotmc.org/wiki/itemstack-serialization/) 。
