### ISSUE TITLE
玩家点击佩戴称号时执行命令

### ISSUE THREAD

**Issue by usernameOHH** [CarmJos/UserPrefix#28]
### **功能简述**
在玩家点击佩戴称号时执行命令，佩戴中可以自己设置延迟执行命令，卸下后执行命令
支持 控制台（最好有{player}这种东西表示玩家名） 玩家 玩家以op身份 执行
默认屏蔽执行命令，提供个命令可以在后台看到执行的命令，方便调试

### **需求来源**
给佩戴称号的人弄些没有任何属性加成的粒子之类的

### **功能参考**(可选)
米饭的 playertitle 插件

### **附加内容**
-

**Comment by CarmJos** [comment]
您好，本功能能将在下一个版本中更新并支持哦~

**Comment by CarmJos** [comment]
您好，功能配置设计如下：

在每个前缀的配置文件中，新增 `actions` 配置节点，它看起来是这样的：

```yaml
# 执行指令 [非必须]
#  用于在玩家选择/取消选择前缀时执行相应动作，以便于实现一些特殊的功能。
#  具体操作类型详见： https://github.com/CarmJos/UserPrefix/tree/master/.documentation/ACTIONS.md
actions:
  select: # 选择这个前缀时执行的操作
    - "[CONSOLE] say %player_name% 选择了 Pro会员前缀 ！"
  cancel: # 取消选择时执行的操作
    - "[CONSOLE] say %player_name% 取下了 Pro会员前缀 ！"
```

具体操作类型请在版本更新后前往 [操作类型配置](https://github.com/CarmJos/UserPrefix/tree/master/.documentation/ACTIONS.md) 页查看哦~
