### ISSUE TITLE
配置文件改了无效

### ISSUE THREAD

**Issue by Hzm20** [CarmJos/UserPrefix#56]
### **问题简述**

改了配置文件那段，玩家前面也不显示

**Comment by CarmJos** [comment]
不清楚您描述的问题哦，请完善议题内容，补充截图、配置文件内容。

**Comment by CarmJos** [comment]
改成 
```yaml
  chat:
    # 是否开启本功能
    enable: false
    # 聊天的格式，注意 “%1$s” 和 “%2$s” 不可缺少。
    # - %1$s -> 玩家名
    # - %2$s -> 聊天内容
    format: <%UserPrefix_prefix%%1$s> %2$s

```

即可。

单纯打开只是接管，必须修改format格式，把prefix的变量添加在前面才可以。
